spring:
    neo4j:
        uri: ${NEO4J_URI:bolt://localhost:7687}
        authentication:
            username: ${NEO4J_USERNAME:neo4j}
            password: ${NEO4J_PASSWORD:123456}
    kafka:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
    cloud:
        stream:
            bindings:
                targetAudienceTopicPublish:
                    destination: ${TARGET_AUDIENCE_TOPIC_PUBLISH:targetAudienceTopicPublish}